Feature/custom logging target
rhythmictech/terraform-aws-backend pull request #4
Opened 2020-06-09 03:39 UTC by mike-rsi

AWS does not recommend saving S3 access logs to the same bucket as this creates an infinite loop of logging (each log file saved generates an additional log file about itself being created, ad infinitum). See: https://aws.amazon.com/premiumsupport/knowledge-center/s3-server-access-logs-same-bucket/

I've created a patch that allows you to customize the target bucket for saving S3 access logs of the TF state bucket to a different, pre-existing S3 bucket.  I've written it in such a way that's it's backwards compatible (i.e. it will be configured to save to itself with the same key as previously if the new variables aren't provided).  I've tested it with both default settings (old behaviour) and overriding with a custom bucket.

Let me know if you have any questions. Thanks!

2020-06-09 16:43 UTC, smiller171 requested changes
Thanks for the PR! Looks good, I'd just like to see a couple minor changes.

2020-06-09 16:43 UTC, smiller171 commented on main.tf
> +    target_bucket = var.logging_target_bucket != "" ? var.logging_target_bucket : var.bucket
I quite like the `coalesce` pattern in this case

```suggestion
    target_bucket = coalesce(var.logging_target_bucket, var.bucket)
```

2020-06-09 16:43 UTC, smiller171 commented on variables.tf
> +  default     = ""
I generally prefer to default to `null` as it's a more explicit "undefined" than an empty string.
```suggestion
  default     = null
```

2020-06-09 16:43 UTC, cdaniluk commented
Love this. This is a tricky issue because we use this bucket for bootstrapping. It’s typically the first bucket in the account and not logging on this bucket would be nuts. We actually thought about making two buckets initially. But in an ideal world this would just find a way to go to a logging bucket post-bootstrap.

2020-06-09 19:38 UTC, sblack4 approved these changes
I like the suggested changes but am less concerned with style than functionality. :shipit:

2020-06-09 19:48 UTC, smiller171 commented
@sblack4 let's just commit my suggestions and merge

2020-06-10 13:38 UTC, cdaniluk approved these changes

2020-06-10 13:47 UTC, merged

2020-06-10 13:47 UTC, cdaniluk commented
Thanks @mike-rsi!

2020-06-10 18:22 UTC, mike-rsi commented
Thanks for the good suggestions/commits @smiller171 and for the merge @cdaniluk.  I see a new issue was created re: creating the logging bucket, so I'll add my thoughts on that topic to the new issue instead of here.  Thanks!

2020-06-10 23:49 UTC, mike-rsi commented
@smiller171 an interesting side effect of setting `logging_target_bucket` to `null` instead of `""` has been revealed now that this has been released.  registry.terraform.io interprets it as being a required variable, even though functionally you don't need to specify it when using the module:
https://registry.terraform.io/modules/rhythmictech/backend/aws/2.1.0?tab=inputs

2020-06-10 23:52 UTC, smiller171 commented
Wow. I'd never noticed that.

I think I'm gonna open a bug with Hashicorp about this, as part of the point of adding a null type was being able to totally omit values